"use client";

/**
 * QR workspace surface.
 *
 * Renders a QR code generated by `lib/devpilot/tools/qr.ts` and
 * exports it as PNG or SVG. Mirrors the tool chrome used by every
 * other DevPilot surface.
 */

import { useState } from "react";
import { Download, QrCode as QrIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useToast } from "../toast";
import { ToolChrome } from "./shared/tool-chrome";
import {
  asQrBody,
  copyToClipboard,
  deleteDevSession,
  downloadTextFile,
  generateQr,
  qrMatrixToSvg,
  type QrMatrix,
  type QrResult,
} from "@/lib/devpilot";
import type { DevSession } from "@/lib/devpilot";

interface QrSurfaceProps {
  session: DevSession;
  onChange: (next: DevSession) => void;
}

const EC_LEVELS: Array<"L" | "M" | "Q" | "H"> = ["L", "M", "Q", "H"];

export function QrSurface({ session, onChange }: QrSurfaceProps) {
  const body = asQrBody(session.body);
  const { toast } = useToast();
  const [rendered, setRendered] = useState<{ matrix: QrMatrix; svg: string } | null>(null);
  const [error, setError] = useState<string | null>(null);

  function commit(patch: Partial<typeof body>) {
    onChange({ ...session, body: { ...body, ...patch } });
    setRendered(null);
  }

  function generate() {
    if (!body.text.trim()) {
      setError("Text is empty");
      setRendered(null);
      return;
    }
    const result: QrResult = generateQr(body.text, body.ecLevel);
    if (!result.ok) {
      setError(result.message);
      setRendered(null);
      return;
    }
    setError(null);
    setRendered({
      matrix: result.matrix,
      svg: qrMatrixToSvg(result.matrix, { moduleSize: body.moduleSize, margin: body.margin }),
    });
  }

  function downloadPng() {
    if (!rendered) return;
    const img = new Image();
    const blob = new Blob([rendered.svg], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    img.onload = () => {
      const canvas = document.createElement("canvas");
      const size = rendered.matrix.length + body.margin * 2;
      const moduleSize = body.moduleSize;
      canvas.width = size * moduleSize;
      canvas.height = size * moduleSize;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        URL.revokeObjectURL(url);
        toast({ message: "Canvas is not available in this browser", tone: "error" });
        return;
      }
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      URL.revokeObjectURL(url);
      canvas.toBlob((pngBlob) => {
        if (!pngBlob) {
          toast({ message: "PNG export failed", tone: "error" });
          return;
        }
        const safe = (session.meta.title || "qr-code")
          .replace(/[^\w\-]+/g, "_")
          .slice(0, 60);
        const a = document.createElement("a");
        a.href = URL.createObjectURL(pngBlob);
        a.download = `${safe}.png`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(a.href);
      }, "image/png");
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      toast({ message: "PNG export failed", tone: "error" });
    };
    img.src = url;
  }

  function downloadSvg() {
    if (!rendered) return;
    const safe = (session.meta.title || "qr-code")
      .replace(/[^\w\-]+/g, "_")
      .slice(0, 60);
    downloadTextFile(rendered.svg, `${safe}.svg`, "image/svg+xml");
  }

  async function copySvg() {
    if (!rendered) {
      toast({ message: "Generate a code first", tone: "info" });
      return;
    }
    const ok = await copyToClipboard(rendered.svg);
    toast({ message: ok ? "SVG copied" : "Could not copy", tone: ok ? "success" : "error" });
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <ToolChrome
        title={session.meta.title}
        description="Generate a QR code and download it as PNG or SVG."
        isFavorite={body.isFavorite}
        onToggleFavorite={async () => {
          commit({ isFavorite: !body.isFavorite });
        }}
        onCopy={copySvg}
        copyLabel="Copy SVG"
        copyDisabled={!rendered}
        onDelete={async () => {
          await deleteDevSession(session.meta.id);
          toast({ message: "Session deleted", tone: "info" });
        }}
        extraActions={
          <Button
            size="sm"
            className="h-8 gap-1.5 px-2.5 text-xs"
            onClick={generate}
          >
            <QrIcon className="h-3.5 w-3.5" aria-hidden="true" />
            Generate
          </Button>
        }
        status={
          error ? (
            <span className="text-destructive">{error}</span>
          ) : rendered ? (
            <span className="text-primary">
              {rendered.matrix.length} × {rendered.matrix.length}
            </span>
          ) : (
            <span className="text-muted-foreground">Press Generate to render the code</span>
          )
        }
      />

      <div className="grid min-h-0 flex-1 gap-3 overflow-y-auto p-4 lg:grid-cols-[2fr,3fr]">
        <Card className="p-3">
          <h3 className="mb-2 text-xs font-semibold">Input</h3>
          <textarea
            value={body.text}
            onChange={(event) => commit({ text: event.target.value })}
            placeholder="Type any text to encode…"
            className="min-h-[180px] w-full rounded-md border border-border bg-background p-2 font-mono text-xs leading-relaxed"
            spellCheck={false}
          />
          <div className="mt-3 grid gap-2 sm:grid-cols-2">
            <label className="flex flex-col gap-1 text-xs">
              <span className="font-medium">Module size</span>
              <input
                type="range"
                min={2}
                max={20}
                value={body.moduleSize}
                onChange={(event) =>
                  commit({ moduleSize: Number(event.target.value) })
                }
                aria-label="Module size"
              />
              <span className="text-[10px] text-muted-foreground">
                {body.moduleSize}px per module
              </span>
            </label>
            <label className="flex flex-col gap-1 text-xs">
              <span className="font-medium">Margin</span>
              <input
                type="range"
                min={0}
                max={10}
                value={body.margin}
                onChange={(event) =>
                  commit({ margin: Number(event.target.value) })
                }
                aria-label="Margin"
              />
              <span className="text-[10px] text-muted-foreground">
                {body.margin} modules of quiet zone
              </span>
            </label>
            <label className="flex flex-col gap-1 text-xs sm:col-span-2">
              <span className="font-medium">Error-correction</span>
              <select
                value={body.ecLevel}
                onChange={(event) =>
                  commit({ ecLevel: event.target.value as typeof body.ecLevel })
                }
                className="h-8 rounded-md border border-border bg-background px-2 text-xs"
                aria-label="Error-correction level"
              >
                {EC_LEVELS.map((level) => (
                  <option key={level} value={level}>
                    {level} (≈
                    {level === "L" ? " 7%" : level === "M" ? " 15%" : level === "Q" ? " 25%" : " 30%"}
                    )
                  </option>
                ))}
              </select>
            </label>
          </div>
        </Card>
        <Card className="flex flex-col items-center justify-center gap-3 p-3">
          {rendered ? (
            <>
              <div
                className="rounded border border-border bg-white p-2"
                dangerouslySetInnerHTML={{ __html: rendered.svg }}
              />
              <div className="flex flex-wrap items-center gap-2">
                <Button
                  size="sm"
                  className="h-7 gap-1.5 px-2 text-xs"
                  onClick={downloadPng}
                >
                  <Download className="h-3 w-3" aria-hidden="true" />
                  Download PNG
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-7 gap-1.5 px-2 text-xs"
                  onClick={downloadSvg}
                >
                  <Download className="h-3 w-3" aria-hidden="true" />
                  Download SVG
                </Button>
              </div>
            </>
          ) : (
            <p className="text-xs text-muted-foreground">
              No code generated yet. Press Generate to render the QR.
            </p>
          )}
        </Card>
      </div>
    </div>
  );
}
